MAINT-27056: Make sure that the chat discussion is displayed from the first essay when clicking on chat icon in the user popover.
exo-addons/chat-application pull request #354
Opened 2020-08-19 13:27 UTC by mdiha

In some cases when a chat room is not already created between two users and that one of the users click on the chat icon in the user popover, the chat room selected is not present in the chat rooms already loaded. In order to fix this issue i made sure to reinitialize the chat rooms to make sure that the selected chat room is loaded.

2020-08-24 12:28 UTC, ahamdi requested changes

2020-08-24 12:28 UTC, ahamdi commented on application/src/main/webapp/vue-app/components/ExoChatApp.vue
> +      // make sure to re-init chat rooms before selecting a room that may be under creation.
Couldn't we reload chat rooms only after creating a new one, inside the ExoChatRoomFormModal.vue

2020-08-24 13:16 UTC, mdiha commented on application/src/main/webapp/vue-app/components/ExoChatApp.vue
> +      // make sure to re-init chat rooms before selecting a room that may be under creation.
This is related to one to one chat rooms they are created only when clicking on the send message button in user popover or in the user profile.

2020-08-25 16:40 UTC, ahamdi approved these changes
LGTM

2020-08-25 16:41 UTC, merged