MAINT-28666: Add the possibility to mention a user in chat
exo-addons/chat-application pull request #359
Opened 2020-09-30 08:29 UTC by AzmiTouil

2020-10-06 17:05 UTC, ahamdi requested changes

2020-10-06 17:05 UTC, ahamdi commented on application/src/test/specs/ExoChatMessageComposer.test.js
> -    expect(cmp.emitted('message-written')).toHaveLength(1);
Couldn't we restore this and check the text length ?

2020-10-06 17:05 UTC, ahamdi commented on application/src/test/specs/ExoChatMessageComposer.test.js
> +  /*it('select emoji', () => {
we should not remove tests :-)

2020-10-06 17:05 UTC, ahamdi commented on application/src/test/specs/ExoChatMessageComposer.test.js
> +  /*document.getSelection found in text-caret.js cannot be called in Jest test*/
COuld you tell me why it could not ?

2020-10-06 17:05 UTC, ahamdi commented on server-embedded/src/main/java/org/exoplatform/chat/services/ChatServiceImpl.java
> +      Elements elements = Jsoup.parse(message).select("a");
You can use java.util.regex package to extract the needed text , please avoid including new dependencies since it i snot required

2020-10-06 23:41 UTC, AzmiTouil commented on application/src/main/webapp/vue-app/components/ExoChatMessageComposer.vue
> +        <div v-else id="messageComposerArea" ref="messageComposerArea" contenteditable="true" style="min-height:50px; width:300px;" name="messageComposerArea" @paste="onPaste" @keydown.enter="prevent
no , it's not required, css already added

2020-10-06 23:42 UTC, AzmiTouil commented on application/src/test/specs/ExoChatMessageComposer.test.js
> -    expect(cmp.emitted('message-written')).toHaveLength(1);
Done !

2020-10-06 23:42 UTC, AzmiTouil commented on application/src/test/specs/ExoChatMessageComposer.test.js
> +  /*it('select emoji', () => {
restored

2020-10-06 23:42 UTC, AzmiTouil commented on server-embedded/src/main/java/org/exoplatform/chat/services/ChatServiceImpl.java
> +      Elements elements = Jsoup.parse(message).select("a");
okay , done !

2020-10-06 23:54 UTC, AzmiTouil commented on application/src/test/specs/ExoChatMessageComposer.test.js
> +  /*document.getSelection found in text-caret.js cannot be called in Jest test*/
This is related to the jest version, this version does not support selection and Ranges, I think it become supported in the latest version.
https://github.com/jsdom/jsdom/pull/2719

2020-10-07 11:12 UTC, ahamdi approved these changes
LGTM

2020-10-07 11:22 UTC, merged