MAINT-36266: Fix sending pasted image process and fix display of chat message composer on FireFox browser after pasting an image.
exo-addons/chat-application pull request #378
Opened 2020-11-13 15:10 UTC by mdiha

*Fix sending pasted image process form chat message composer:
Some images from browsers have a source url encoded to base64 format which contains characters as "+", and in cat message composer there is a shortcut for creating tasks by the "+" character so the pasted image is consider as adding a task and it throws an uncaught error, so i made sure to check whether it is an image or a simple text.
-Fix display of message composer when pasting an image on FireFox browser:
I changed the Vue js conditional rendering "v-if" to "v-show" for the element 'apps-container' since it has css transition property which crashes when adding an image in the content editable message composer of the chat.

2020-11-13 17:21 UTC, ahamdi requested changes

2020-11-13 17:21 UTC, ahamdi commented on application/src/main/webapp/vue-app/components/ExoChatMessageComposer.vue
> +          if(application.shortcutMatches && application.shortcutMatches(newMessage) && !newMessage.includes('<img src=')) {
Could you just remove the image from the message before passing the message to the application shortcuts

2020-11-16 09:00 UTC, mdiha commented on application/webpack.dev.js
> +    path: path.resolve(__dirname, exoServerPath + '/webapps/chat/')
Okay will revert this change

2020-11-16 09:00 UTC, mdiha commented on application/src/main/webapp/vue-app/components/ExoChatMessageComposer.vue
> +          if(application.shortcutMatches && application.shortcutMatches(newMessage) && !newMessage.includes('<img src=')) {
Done

2020-11-16 10:51 UTC, ahamdi requested changes

2020-11-16 10:51 UTC, ahamdi commented on application/src/main/webapp/vue-app/components/ExoChatMessageComposer.vue
> +      if (newMessage.includes('<img src=')) {
Could you use a regex for this like : 
`newMessage.replaceAll(/<img src="data:image\/.*;base64[^>]*>/g,'');`

2020-11-16 10:57 UTC, mdiha commented on application/src/main/webapp/vue-app/components/ExoChatMessageComposer.vue
> +      if (newMessage.includes('<img src=')) {
Okay

2020-11-16 11:42 UTC, ahamdi approved these changes

2020-11-16 11:45 UTC, merged